### ISSUE TITLE
orientation of plots labels

### ISSUE THREAD

**Issue by tdemarchin** [ekstroem/dataMaid#14] opened 2017-08-30 07:52 UTC
Hi, 
Thank you for creating this incredible package!
I started to use it yesterday and I think it will greatly help my work.
I just have a problem with the x-axis labels of the plots for character variables: the text overlap with some (see the attached file). Would it be possible to rotate the labels of the plots or to increase their size to avoid any overlap?
Thank you again,
Thomas.
![2017-08-30 09_48_37-datamaid_data pdf - adobe acrobat reader dc](https://user-images.githubusercontent.com/31469123/29861233-e216a384-8d68-11e7-95f7-54a386686c74.png)

**Comment by annennenne** [comment] 2017-09-08 09:10
Hi Thomas, thanks a lot for your input! It's very much appreciated.

What you're asking is really a tricky question that we have also been aware of. The problem is that what kinds of labels are nice to have really depends a lot on the data. For instance, if all the labels are very long, but the categorical variables only take a few values, horizontal labels might be prefered, whereas in your scenario above, vertical labels are clearly better. We have not yet found a systematic way to solve this issue.

But I would like to use this as an opportunity to showcase how `dataMaid` can be customized by addding an additional visual function. If this gets too technical for you, feel free to just use the code bit in the middle and ignore the general tutorial. In any case, it should do what you are asking for.


So here is a bit of code for defining a new visual function. Note that this is the most thorough approach and that several shortcuts are available (see the documentation of `visualFunction` for more on this). 

```  
#Define a generic function that can dispath all calls according to the class of v
vertLabStandardVisual <- function(v, vnam, doEval = TRUE) UseMethod("vertLabStandardVisual")

#assign methods to generic standardVisual function for each relevant data class
#note: For variables that are not character, factor, labelled or logical, we just use
#the usual standardVisual function
vertLabStandardVisual.character <- function(v, vnam, doEval = TRUE) vertLabStandardVisualCFLB(v, vnam, doEval=doEval)
vertLabStandardVisual.factor <- function(v, vnam, doEval = TRUE) vertLabStandardVisualCFLB(v, vnam, doEval=doEval)
vertLabStandardVisual.labelled <- function(v, vnam, doEval = TRUE) vertLabStandardVisualCFLB(haven::as_factor(v), 
                                                                               vnam, doEval=doEval)
vertLabStandardVisual.numeric <- function(v, vnam, doEval = TRUE) standardVisual(v, vnam, doEval=doEval)
vertLabStandardVisual.integer <- function(v, vnam, doEval = TRUE) standardVisual(v, vnam, doEval=doEval)
vertLabStandardVisual.logical <- function(v, vnam, doEval = TRUE) vertLabStandardVisualCFLB(v, vnam, doEval=doEval)
vertLabStandardVisual.Date <- function(v, vnam, doEval = TRUE) standardVisual(v, vnam, doEval=doEval)


#This will add vertLabStandardVisual to the visualFunction-overview obtained by
#calling allVisualFunctions()
vertLabStandardVisual <- visualFunction(vertLabStandardVisual,
      "Histograms and barplots using ggplot2 with vertical labels for categorical variables",
      allClasses())


#A helper function
vertLabPlot <- function(x, xlab, main) {
  qplot(x = x, xlab = xlab, main = main) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
}


#A visualFunction for character, factor, labelled and logical variables
vertLabStandardVisualCFLB <- function(v, vnam, doEval = TRUE) {
  v <- dataMaid:::escapeRStyle(na.omit(v))
  if (identifyNums(v, nVals = 0)$problem) {
    v <- as.numeric(as.character(v))
  }
  v <- factor(v)
  thisCall <- call("vertLabPlot", x=v, xlab="", main=vnam)
  if (doEval) {
    return(eval(thisCall))
  } else return(deparse(thisCall))
}
```

and now you would be able to create a report with vertical labels for character/factor/logical variables by calling

``` 
data(toyData)
clean(toyData, allVisuals = "vertLabStandardVisual", replace = TRUE)
```

**Comment by ekstroem** [comment] 2017-09-09 17:28
I think Anne's solution is the best option right now - define your own custom plot function and use that instead. It's difficult to find a one-plot-suits-all solution which is why we went with the default horisontal labels. Closing this for now - reopen if the answer/solution doesn't work

**Closed as completed by ekstroem** 2017-09-09 17:28 UTC
Labels: enhancement

**Comment by tdemarchin** [comment] 2017-09-09 18:19
Dear Anne and Ekstroem, thank you for your fast and extensive reply! 
I understand it is difficult to find a solution which works for all cases. 
I will try your solution next week at work. 
Have a nice Sunday, 
Thomas.
