### ISSUE TITLE
Pander error 43: File not found

### ISSUE THREAD

**Issue by nielsoledam** [ekstroem/dataMaid#1] opened 2017-02-07 12:13 UTC
Hi Claus

I saw your excellent talk last week at Data Science Day 2017 and wanted to try out your DataMaid package. And I must say, that it's really great and easy to use!
:-)

However I got the following error when I tried to use it on a dataframe that contained character values that had \n in them:
> Data cleaning is finished. Please wait while your output file is being rendered.
> ! Undefined control sequence.
> l.563 \n
> 
> pandoc: Error producing PDF
> Error : pandoc document conversion failed with error 43
> Error in pander::openFileInOS(outFile) : File not found!

Not a big deal, as I can just exclude the variable in question, but I guess it's an issue you can easily address in an upcoming update.

Niels

System:
R version 3.3.2, Mac OS Sierra
dataMaid v0.9.2

**Comment by ekstroem** [comment] 2017-02-07 15:24
Can you give a reproducible example. If I try

```{r}
library(dataMaid)
toyData$var7 <- as.character(toyData$var1)
toyData$var7[2] <- "red\n"
toyData$var7[3] <- "red\\nqw"
toyData$var7[4] <- "red\r"
toyData$var7[5] <- "red\\rqwe"
clean(toyData, replace=TRUE)
```
then everything appears to work. My data frame looks like this:

```
1   red    1     a -0.6264538    1 Irrelevant       red
2   red    1     a  0.1836433    2 Irrelevant     red\n
3   red    1     a -0.8356286    3 Irrelevant  red\\nqw
4   red    2     a  1.5952808    4 Irrelevant     red\r
5   red    2     a  0.3295078    5 Irrelevant red\\rqwe
6   red    6     b -0.8204684    6 Irrelevant       red
7   red    6     b  0.4874291    7 Irrelevant       red
8   red    6     b  0.7383247    8 Irrelevant       red
9   red  999     c  0.5757814    9 Irrelevant       red
10  red   NA     c -0.3053884   10 Irrelevant       red
11 blue    4     c  1.5117812   11 Irrelevant      blue
12 blue   82     .  0.3898432   12 Irrelevant      blue
13 blue   NA       -0.6212406   13 Irrelevant      blue
14 <NA>  NaN other -2.2146999   14 Irrelevant      <NA>
15 <NA>    5 OTHER  1.1249309   15 Irrelevant      <NA>
```

**Comment by annennenne** [comment] 2017-02-07 15:57
Thanks for your feedback Niels! Even though we have addressed escaped character issues in the summarize- and check-steps of clean(), we have forgotten to do it in the visualize-step. Therefore, a likely explanation for your error is that it occurs because non-valid axis-ticks are supplied in the plots. I cannot reproduce your error myself, but I suspect that it might be due to differences in versions of ggplot2, which is used for plotting.

I would therefore very much like to see the outputs (i.e. errors/warnings) of the following commands, using Claus' modified toyData from above and/or a different example where your error occurs:

```{r, eval = F}
clean(toyData, replace = TRUE)
clean(toyData, replace = TRUE, allVisual = "basicVisual")
clean(toyData, replace = TRUE, mode = c("summarize", "check"))
clean(toyData, replace = TRUE, allVisual = "basicVisual", mode = c("summarize", "check"))
```

This issue will of course be fixed in the next update of dataMaid.

**Comment by nielsoledam** [comment] 2017-02-07 16:57
None of the four commands you have noted gives me any errors or warnings.

They all work as expected, i.e. produces the expected output files with the following message:
> Data cleaning is finished. Please wait while your output file is being rendered.

I've looked closer into my data, and the issue seems to be triggered by the data in my textvariable being pretty messy. To be precise it has the following issues:

- Encoding is "unknown".
- It contains html-code.
- It contains both \n and \\n.

I've included a RDS-dump of the specific part of the dataframe that triggers the issue.
[error_causing_df.rds.zip](https://github.com/ekstroem/dataMaid/files/758393/error_causing_df.rds.zip)

You should be able to trigger the issue by running the following code:
```
library(dataMaid)
x <- readRDS("error_causing_df.rds")
clean(x);
```

**Comment by ekstroem** [comment] 2017-02-08 15:04
Anne just fixed it with her recent update. Get the github version and try it out

**Closed as completed by ekstroem** 2017-02-08 15:04 UTC
Labels: bug

**Comment by nielsoledam** [comment] 2017-02-08 15:17
Yes, that fixed the issue.
:-D
