### ISSUE TITLE
LaTeX detection fail on Windows 10

### ISSUE THREAD

**Issue by annennenne** [ekstroem/dataMaid#28] opened 2018-05-18 11:55 UTC
In the eRum2018 workshop, we experienced that `makeDataReport()` tried doing a pdf report even though the user had no LaTeX installation. The user was running Windows 10.

**Comment by annennenne** [comment] 2018-05-18 14:56
This problem also occurs in Windows 10 if there are non-standard characters in the variable names. rmarkdown makes an error message indicating that there is no TeX installation (even when there is), however, the problem goes away if the variable names are changed in the .rmd file. 

The problem seems to be due to the variable names not being properly escaped in the "Summary table". (toc).

**Comment by ekstroem** [comment] 2018-09-11 22:04
I cannot reproduce the error with my current installation on Windows 10. Can you give an example of a non-standard variable name that throws an error?

**Comment by annennenne** [comment] 2018-09-12 07:20
I haven't encountered the bug myself (I'm just reporting what users have told me), so unfortunately, I can't give you a minimal example.

**Comment by ekstroem** [comment] 2018-10-03 10:13
Closing this until we can reproduce it

**Closed as completed by ekstroem** 2018-10-03 10:13 UTC
Labels: bug
